server {
  listen 80;

  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    # Esta es la línea mágica:
    # Intenta servir el archivo solicitado ($uri), luego intenta servirlo como un directorio ($uri/),
    # y si nada de eso funciona, devuelve /index.html.
    try_files $uri $uri/ /index.html;
  }

  # Opcional: Mejora el cacheo de los archivos estáticos
  location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg)$ {
    expires 1y;
    add_header Cache-Control "public";
  }
}